/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.hyunseda.market.presentation;

import co.com.hyunseda.market.domain.Product;
import co.com.hyunseda.market.infra.Observer;
import co.com.hyunseda.market.service.CategoryService;
import co.com.hyunseda.market.service.ProductService;
import java.util.ArrayList;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Libardo Pantoja, Julio A. Hurtado
 */
public class GUICart extends javax.swing.JDialog implements Observer{
    private ProductService productService;
    private CategoryService categoryService;
    private List<Product> atrProductList = new ArrayList<>();
    /**
     * Creates new form GUIProductsFind
     * @param productService
     */
    public GUICart(ProductService productService) {
        this.productService = productService;
        initComponents();
        initializeTable();
        fillCombo();
        
        //setLocationRelativeTo(null); //centrar al ventana
    }
    
    private void initializeTable() {
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id", "Name", "Price"
                }
        ));
    }
    
    private void fillTable(List<Product> prmProductList) {
    initializeTable();
    
    
    DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();

    Object rowData[] = new Object[3];//No columnas
        
        for (int i = 0; i < prmProductList.size(); i++) {
            rowData[0] = prmProductList.get(i).getProductId();
            rowData[1] = prmProductList.get(i).getName();
            rowData[2] = prmProductList.get(i).getPrice();

            model.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlCenter = new javax.swing.JPanel();
        pnlCbx = new javax.swing.JPanel();
        cbxProducts = new javax.swing.JComboBox<>();
        pnlButtonList = new javax.swing.JPanel();
        btnAddCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        pnlNorth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlSouth = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnGoCart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Búsqueda de productos");

        pnlCenter.setLayout(new java.awt.BorderLayout());

        pnlCbx.setLayout(new java.awt.GridLayout(1, 2));

        cbxProducts.setToolTipText("");
        cbxProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxProducts.setName(""); // NOI18N
        cbxProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProductsActionPerformed(evt);
            }
        });
        pnlCbx.add(cbxProducts);

        btnAddCart.setText("Agregar al carrito");
        btnAddCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCartActionPerformed(evt);
            }
        });
        pnlButtonList.add(btnAddCart);

        pnlCbx.add(pnlButtonList);

        pnlCenter.add(pnlCbx, java.awt.BorderLayout.PAGE_START);

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Cantidad"
            }
        ));
        tblProducts.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblProducts);
        tblProducts.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        pnlCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("HYUNSEDA STORE");

        javax.swing.GroupLayout pnlNorthLayout = new javax.swing.GroupLayout(pnlNorth);
        pnlNorth.setLayout(pnlNorthLayout);
        pnlNorthLayout.setHorizontalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNorthLayout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(266, 266, 266))
        );
        pnlNorthLayout.setVerticalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNorthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlNorth, java.awt.BorderLayout.PAGE_START);

        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnGoCart.setBackground(new java.awt.Color(255, 0, 0));
        btnGoCart.setForeground(new java.awt.Color(255, 255, 255));
        btnGoCart.setBorder(null);
        btnGoCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSouthLayout = new javax.swing.GroupLayout(pnlSouth);
        pnlSouth.setLayout(pnlSouthLayout);
        pnlSouthLayout.setHorizontalGroup(
            pnlSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSouthLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(btnClose)
                .addGap(18, 18, 18)
                .addComponent(btnGoCart, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSouthLayout.setVerticalGroup(
            pnlSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSouthLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGoCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        getContentPane().add(pnlSouth, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
        GUIUserMen userMen = new GUIUserMen(productService, categoryService);
        userMen.setVisible(true);
        
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCartActionPerformed
        Product objProduct = productService.findPorName(cbxProducts.getSelectedItem().toString());
        atrProductList.add(objProduct);
        fillTable(atrProductList);
    }//GEN-LAST:event_btnAddCartActionPerformed

    private void cbxProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductsActionPerformed
        
    }//GEN-LAST:event_cbxProductsActionPerformed

    private void btnGoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoCartActionPerformed

    /**
     *@brief función que llena el comboBox de manera automática
     */
    private void fillCombo(){
        int max = productService.listProducts().size();//Obtener el tamaño de la lista de productos
        for(int i = 0; i < max;i++)//Hacer el recorrido
        {
            cbxProducts.addItem(productService.listProducts().get(i).getName());//LLenado del comboBox
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCart;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGoCart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxProducts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlButtonList;
    private javax.swing.JPanel pnlCbx;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JPanel pnlSouth;
    private javax.swing.JTable tblProducts;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Object o) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
